### ISSUE TITLE
Breaking with next.js 13 app folder

### ISSUE THREAD

**Issue by gaetleba** [kwonoj/swc-plugin-coverage-instrument#183] opened 2022-11-07 12:47 UTC
Hi, I'm not sure if this is a problem with the plugin or Next but here is a bug I'm encountering :
Trying to use this plugin with a Next.js project and the latest next feature app folder I get the following bug:
```
error - (sc_server)\node_modules\next\dist\shared\lib\app-router-context.js (10:40) @ eval
error - TypeError: _react.default.createContext is not a function
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/shared/lib/app-router-context.js:297:77)
    at Object.(sc_server)/./node_modules/next/dist/shared/lib/app-router-context.js (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\app\page.js:920:1)
    at __webpack_require__ (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/app-router.js:2314:61)
    at Object.(sc_server)/./node_modules/next/dist/client/components/app-router.js (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\app\page.js:197:1)
    at __webpack_require__ (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fpage&appPaths=%2Fpage&pagePath=private-next-app-dir%2Fpage.tsx&appDir=C%3A%5CUsers%5CWarrows%5Cworkspace%5Crepronext%5Cswc-coverage%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=C%3A%5CUsers%5CWarrows%5Cworkspace%5Crepronext%5Cswc-coverage&isDev=true&tsconfigPath=tsconfig.json!:28:24)
    at Object.(sc_server)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fpage&appPaths=%2Fpage&pagePath=private-next-app-dir%2Fpage.tsx&appDir=C%3A%5CUsers%5CWarrows%5Cworkspace%5Crepronext%5Cswc-coverage%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=C%3A%5CUsers%5CWarrows%5Cworkspace%5Crepronext%5Cswc-coverage&isDev=true&tsconfigPath=tsconfig.json! (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\app\page.js:99:1)
    at __webpack_require__ (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (C:\Users\Warrows\workspace\repronext\swc-coverage\.next\server\app\page.js:974:39) {
  page: '/'
}
null
```
Using the same project with babel and `babel-plugin-istanbul` works fine.
Here is a reproduction project : https://github.com/gaetleba/swc-plugin-coverage-instrument-bug-reproduction
I made a report over there too: https://github.com/vercel/next.js/issues/42580

**Comment by kwonoj** [comment] 2022-11-07 16:39
Looks like plugin affects something, probably not a bug in next.js upstream.

**Comment by kwonoj** [comment] 2022-11-13 00:25
Looks like there's common symptom when custom transform / plugin is enabled: https://github.com/vercel/next.js/issues/41994

**Comment by divramod** [comment] 2023-02-02 07:58
@gaetleba where you somehow able to fix this issue with the experimental app feature?

**Comment by gaetleba** [comment] 2023-02-03 15:56
> @gaetleba where you somehow able to fix this issue with the experimental app feature?
No, I'm using babel for now

**Comment by kwonoj** [comment] 2023-04-25 04:25
I've been peeking this bit, this is mostly due to server component side transform error. I can't explain why it occurs with this specific plugin, as well as cannot change plugin's behavior to amend it (since I don't have explanation why server component is being affected). 

I'm going to close this for now. If anyone have minimal reproduction which doesn't have server component involved and transforming with this plugin creates offending codes, I may able to look into.

**Closed by kwonoj** 2023-04-25 04:25 UTC

**Comment by boylec** [comment] 2024-08-28 20:56
does that mean this plugin will break on server components
