### ISSUE TITLE
Unable to load plugin on NextJS 12.3.3

### ISSUE THREAD

**Issue by h2oearth** [kwonoj/swc-plugin-coverage-instrument#229] opened 2024-03-16 10:14 UTC
I tried every available release of your plugin, and I have the same error message when I start my app. Am I missing something?

This is my configuration. 
```
  experimental: {
    swcPlugins: [['swc-plugin-coverage-instrument', {}]],
  },
```

This is the error that I get when I starts my app
```
Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__lookup_char_pos_source_map_proxy": incompatible import type. Expected Function(FunctionType { params: [I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32], results: [I32] })', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.226.26/src/plugin.rs:216:14
error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/Users/dodo/wrk/my-project/node_modules/next/dist/client/dev/amp-dev.js")'
```

**Comment by kwonoj** [comment] 2024-03-16 17:52
I tried few old versions and seems working for me. Closing as dupe of https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/225.

**Closed by kwonoj** 2024-03-16 17:52 UTC

**Comment by h2oearth** [comment] 2024-03-17 01:45
Like I said a tried ALL the versions and have the same result
