### ISSUE TITLE
Instrumentation of node_module files

### ISSUE THREAD

**Issue by mskNeo** [kwonoj/swc-plugin-coverage-instrument#204] opened 2023-03-23 03:26 UTC
When I tried to instrument my Next.JS app with the plugin, it would also instrument all js files in node_modules. Is there a way to specify what files to instrument or is that not supported yet?

**Comment by kwonoj** [comment] 2023-03-23 03:28
I guess this is dupe of https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/197

The way I design this is a low level parity to istanbul. If istanbul have an interface and implementation I might mimic as shared in the issue's comment.

**Closed** 2023-03-23 06:01 UTC
